partial_charge:
  method: am1bcc
  # method: am1bccelf10
  # method: espaloma
  # method: nagl
  settings:
    off_toolkit_backend: ambertools
    # off_toolkit_backend: openeye  # required for the am1bccelf10 method
    number_of_conformers: null  # null specifies the use of the input conformer, a value requests that a new conformer be generated
    # nagl_model: null  # null specifies the use of the latest nagl model
